### ISSUE TITLE
Multi-class object tracking and new position estimation without detection result

### ISSUE THREAD

**Issue by rose-jinyang** [NirAharon/BoT-SORT#1]
Hello
How are you?
Thanks for contributing to this project.
I have two questions for this repo.
Does this repo support multi-class multi-object tracking?
Does this method estimate a new position without detection result?

**Comment by NirAharon** [comment]
Hi, the code currently doesn't support multi-class or estimation of new positions without any detection. I am hoping to update these in the next few days.

**Comment by NirAharon** [comment]
The code was updated to support multi-class and estimate new positions without detection.
Please refer to mc_bot_sort.py and mc_demo.py.
