### ISSUE TITLE
multi-class

### ISSUE THREAD

**Issue by ajtao** [NirAharon/BoT-SORT#13]
Hi @NirAharon ,

I noticed that you implemented support for multi-class, which is great. I also saw that it looks like class is resolved with a vote, which is an interesting way to handle things. Another implementation I've seen has isolated classes from each other such that a given track can only have one class identity. I was curious if you'd thought of this other way. I'm honestly not sure whether it'd make a huge amount of difference but it does seem like isolating classes from each other might be a good idea.

**Comment by wsw321** [comment]
Hi，did you refer the implementation of [CaptainEven/MCMOT](https://github.com/CaptainEven/MCMOT) ?, I have seen this  repo for a long time.

**Comment by liuyiche** [comment]
Indeed, I also believe that isolating the classes would be more reasonable. Recently, I worked on a project that involved detecting both heads and full-body people, and the current approach led to tracking confusion.
