### ISSUE TITLE
how to train fastreid on multi-class ?

### ISSUE THREAD

**Issue by wsw321** [NirAharon/BoT-SORT#16]
how to train fastreid on multi-class ? It seems only one class support ReID.

**Comment by NirAharon** [comment]
I think you should try to ask this question at the FastReID repo, I didn't try this.  
Some solutions that I think may work:
1. Train a network with one class by setting your dataset accordingly. Sort the dataset ID as follow: from 1 to N person, from N to N + M cars, and so on.
2. If you don't have many classes you can train network for each class. 
In any case, pay attention that different classes may need different patch input shape (e.g. person 128x256, car 256x256).
Good luck!
