### ISSUE TITLE
CMC

### ISSUE THREAD

**Issue by biibabu** [NirAharon/BoT-SORT#18]
Thank you for your wonderful work! I have a question, can CMC module be used for other trackers, such as JDE? How to use it? Looking forward to your reply, thank you again.

**Comment by NirAharon** [comment]
Hi, the CMC module can be integrated into other trackers.
You will need to copy the following parts:
1. Add tracker/gmc.py to your project.
2. In tracker/bot_sort.py you will need the multi_gmc function, lines 68-83. Maybe you will need to change the tracklet struct according to your code.
3. Add to your tracker constructor the following line: tracker/bot_sort.py line 228. 
4. Add to your tracker after the KF prediction step, the code from: tracker/bot_sort.py lines 297-301. 
Good luck!

**Comment by biibabu** [comment]
thanks,i will try it.

**Comment by xifen523** [comment]
According to your description, I have ported the CMC module to byteTrack, but did not get the expected results.
My specific approach is as follows:


1、In the file byte_tracker.py, add self.warpMatrix = {}, in order to save the warp matrix.
```
class BYTETracker(object):
    def __init__(self, args, frame_rate=30):
        self.tracked_stracks = []  # type: list[STrack]
        self.lost_stracks = []  # type: list[STrack]
        self.removed_stracks = []  # type: list[STrack]

        self.frame_id = 0
        self.args = args
        #self.det_thresh = args.track_thresh
        self.det_thresh = args.track_thresh + 0.1
        self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)
        self.max_time_lost = self.buffer_size
        self.kalman_filter = KalmanFilter()
        self.warpMatrix = {}
        self.getWarpMatrix(args.gcm)

    def getWarpMatrix(self, gcm_para):
        # 读取gcm_para文件中数据，存入warpMatrix中
        with open(gcm_para, 'r') as f:
            # 按行读取，直到读取完毕
            while True:
                line = f.readline()
                tokens = line.split("\t")
                if len(tokens) < 7:
                    break
                H = np.eye(2, 3, dtype=np.float_)
                H[0, 0] = float(tokens[1])
                H[0, 1] = float(tokens[2])
                H[0, 2] = float(tokens[3])
                H[1, 0] = float(tokens[4])
                H[1, 1] = float(tokens[5])
                H[1, 2] = float(tokens[6])
                self.warpMatrix[int(tokens[0])] = H
```


2、Camera motion compensation after Kalman prediction

```
        ''' Step 2: First association, with high score detection boxes'''
        strack_pool = joint_stracks(tracked_stracks, self.lost_stracks)
        # Predict the current location with KF
        STrack.multi_predict(strack_pool)

        # Fix camera motion
        warp = self.warpMatrix.get(self.frame_id, np.eye(2, 3))
        STrack.multi_gmc(strack_pool, warp)
        STrack.multi_gmc(unconfirmed, warp)
```

+ The multi_gmc function is source code and has not been modified

**Comment by Bian-666** [comment]
> thanks,i will try it.

Have you added CMC to JDE? I added it according to the above steps, but the result was very poor.
