### ISSUE TITLE
Can pretrained models for yolox and yolov7 be provided?

### ISSUE THREAD

**Issue by Chang-007** [NirAharon/BoT-SORT#19]

**Comment by NirAharon** [comment]
The models trained on the COCO dataset are available at YOLOX and YOLOv7 repositories.
The YOLOX models trained on the MOTChallenge datasets are available at the ByteTrack repository.
I will be releasing the YOLOv7 models for MOTChallenge soon.

**Comment by HanGuangXin** [comment]
@NirAharon Thanks for the work. I'm curious about the difference of metrics when using YOLOX and YOLOv7.
