### ISSUE TITLE
Question about FPS

### ISSUE THREAD

**Issue by winterfell2021** [NirAharon/BoT-SORT#22]
Hi there, thanks for your great work! I used BoT-SORT with yolov7-e6e backbone on my custom datasets, which may have about 100 reid on different classes. I got nearly 5 FPS using all default config but 1920x1920 img size, I use time module to find the reason. I found
```
warp = seslf.gmc.apply(img, dets)
STrack.multi_gmc(strack_pool, warp)
STrack.multi_gmc(unconfirmed, warp)
```
cost about 0.2 second, its that normal?

**Comment by NirAharon** [comment]
Hi, this behavior is expected for large image size.
I thinking on 3 strategies that may work for increasing the FPS in this case:
1. Try to downscale the image by changing the downscale to 4:
https://github.com/NirAharon/BoT-SORT/blob/a720e0490c6613dacccc0088f8c39c61725f1a63/tracker/gmc.py#L8
2. Depend on the GMC method you choose to use. You can reduce the number of the detected keypoints. 
3. You can change the FAST keypoints detection and the ORB feature extraction to run on the GPU using the OpenCV cuda implementation.

I hope I managed to help you, good luck!

**Comment by winterfell2021** [comment]
Thanks for your kind and useful reply, i will take a try. Thx!!
