### ISSUE TITLE
Problem with loading ReID model.

### ISSUE THREAD

**Issue by JovanBosic** [NirAharon/BoT-SORT#26]
Loading checkpoint from pretrained/mot17_sbs_S50.pth
Skip loading parameter 'heads.weight' to the model due to incompatible shapes: (487, 2048) in the checkpoint but (0, 2048) in the model! You might want to double check if this is expected.
Some model parameters or buffers are not found in the checkpoint:
  heads.weight

Can you help me with this? I would like to use ReID model during tracking.

**Comment by danialghlm** [comment]
![Screenshot 2022-08-05 190839](https://user-images.githubusercontent.com/69577658/183100338-5ea64df8-90ce-4e9b-a230-204735b8f42c.jpg)


I think we have same problem,
What should I do ?

**Comment by JovanBosic** [comment]
Actually its not the same problem. Checkpoint loading is done in your case. In my its not.

**Comment by JovanBosic** [comment]
@danialghlm you should just comment the line of a code where you plotting these figures, and you will be fine.

**Comment by NirAharon** [comment]
Hi [JovanBosic](https://github.com/JovanBosic),
I believe it is fine, because the message indicates that only the FC layer in the head skips the loading. 
This FC layer is used in the training for ID loss and dropped during inference.

**Comment by JovanBosic** [comment]
Hi @NirAharon , 
Thank you for your response.

**Comment by staxc** [comment]
Hello @JovanBosic , I also encountered this problem, what I want to ask is how to do to skip this weight does not correspond to the problem, continue to get the tracking results.
