### ISSUE TITLE
About track extrapolations for missing detections

### ISSUE THREAD

**Issue by sudospike** [NirAharon/BoT-SORT#29]
Thanks for your great work. It helped me much in my projects. I have a question about track extrapolations for missing detections mentioned in your paper. Is there some codes about this? Can you tell me more about this?  @NirAharon

**Comment by NirAharon** [comment]
Hi, thank you! 
Yes, it is nothing new. 
If the tracker can correct the camera motion, the predictions of the Kalman filter can be used to track extrapolations.
In the code, I just output tracks that matched or unmatched for one frame.
