### ISSUE TITLE
How to set tracking classes in "mc_demo.py"？

### ISSUE THREAD

**Issue by HLH13297997663** [NirAharon/BoT-SORT#30]
HI, This is a nice work of tracking task, I have a question about the scripts:
I want to realize multi-target tracking, bug i don‘t kown Where to set the tracking classesin "mc_demo.py",  What should I do? 
And What's the different of "mc_demo.py" and "mc_demo_yolov7.py"?

**Comment by NirAharon** [comment]
Hi, thank you.
The "mc_demo.py" is for the YOLOX object detector and "mc_demo_yolov7.py" is for the YOLOv7 object detector.
"mc_demo.py" is based on YOLOX code and it doesn't contain masking of classes as in YOLOVv5/7.
