### ISSUE TITLE
the problem of Kalman Filter

### ISSUE THREAD

**Issue by EnzoLiang** [NirAharon/BoT-SORT#31]
Hi @NirAharon , when I use Kalman Filter  predict mean and covariance, I find the value of mean[1](center y) sometimes is negative. It seems to be unreasonable.  Besides, the parameters of the set noise factors on the paper are applicabel to 30 FPS. How should I adjust it if i use it 25 FPS

**Comment by NirAharon** [comment]
Hi @EnzoLiang
1. The Kalman filter mean[0:1] (center x, center y) might be negative when the object is near the border of the image or leaving the image, is this the case?
2. For 25 FPS the noise factors will approximately be the same, so no change needs to be made.

**Comment by EnzoLiang** [comment]
> 
Hi @NirAharon, I tried to  test it with the default parameters in 25 fps, it seems to be normal. When I sample video with 5 fps and test with the default parameters, it seems to be abnormal. How to adjust the parameters ?

> Hi @EnzoLiang
> 
> 1. The Kalman filter mean[0:1] (center x, center y) might be negative when the object is near the border of the image or leaving the image, is this the case?
> 2. For 25 FPS the noise factors will approximately be the same, so no change needs to be made.

**Comment by NirAharon** [comment]
Hi @EnzoLiang, sorry for the late response. 
Did you manage to adjust the parameters correctly?
