### ISSUE TITLE
Doubts about reid

### ISSUE THREAD

**Issue by Stephen-Ning** [NirAharon/BoT-SORT#47]
Hello! I want to ask if I am using demo When the. py file tests its own video.
"Python3 tools/demo.py video -- path<path_to_video>- f yolox/expos/example/mot/yolox_x_mix_det.py - cprepared/bytetrack_x_mot17. pth. tar -- with reid -- fuse score -- fp16 -- fuse -- save_result" 
Does this commcommand line call the reid module?and line call the reid module?

**Comment by NirAharon** [comment]
Hello, I am not quite sure I understand your question but the ReId should work in this case:
"Python3 tools/demo.py video -- path<path_to_video>- f yolox/expos/example/mot/yolox_x_mix_det.py - cprepared/bytetrack_x_mot17. pth. tar **-- with reid** -- fuse score -- fp16 -- fuse -- save_result"

**Comment by Stephen-Ning** [comment]
OK, thank you for your reply! thank!
