### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Melikamuliyih** [NirAharon/BoT-SORT#5]
File "/root/userfolder/BoT-SORT/fast_reid/fastreid/data/datasets/mot17.py", line 79, in process_dir
    pid, camid = map(int, pattern.search(img_path).groups())
AttributeError: 'NoneType' object has no attribute 'groups'

anyone facing this problem please?

**Comment by NirAharon** [comment]
Hi, may you provide more information? Are you trying to train the ReID net?
It seems that img_path is None.

**Comment by Melikamuliyih** [comment]
yes I'm trying to train the ReID.

**Comment by Melikamuliyih** [comment]
I have generated the MOT17-ReID datasets and set the path but still get the same error? I couldnt get it why

**Comment by NirAharon** [comment]
The argument of MOT17 was not connected properly, which resulted in the incorrect creation of the ReID dataset. Delete the previously generated MOT17-ReID and try again.

**Comment by 15689933561** [comment]
Why do I report an error when I regenerate again

**Comment by dddst123** [comment]
It is caused by the fact that when reading the name sequence number as a tag, the regular expression does not match the name
just change the 
`pattern = re.compile(r'([-\d]+)_MOT17-([-\d]+)-FRCNN')`
in line 82 in    ./fast_reid/fastreid/data/datasets/mot17.py
