### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by piggi999** [NirAharon/BoT-SORT#50]
The OpenCV downloaded now has no 'videostab' folder. Which version of opencv do you use? Can you share the 'videostab' folder?

**Comment by NirAharon** [comment]
Hi, I build the OpenCV library with the OpenCV-Contrib. 
Follow [opencv-contrib installation](https://docs.opencv.org/4.6.0/d7/d9f/tutorial_linux_install.html).

**Comment by piggi999** [comment]
Why is the result of  'main.cpp' code different from the result you uploaded to github?

**Comment by NirAharon** [comment]
Hi @piggi999, 
I used a different standalone project and not this repo. So, maybe I copied the wrong version of the code. 
I just merged this repo with the correct version of the code, so you should successfully regenerate the results I got.
Thank you!

**Comment by piggi999** [comment]
The results are exactly the same. Thank you very much.
