### ISSUE TITLE
speed of demo?

### ISSUE THREAD

**Issue by ajtao** [NirAharon/BoT-SORT#6]
Is the expectation that the demo runs at around 4.3fps at 1280x720? I thought I saw mention of 30fps in the paper. Wondering if i have something configured wrong.

**Comment by ajtao** [comment]
Oh so i did turn off reid and found that i'm at 15fps now. So i suppose my framerate is largely dependent on that. The quality of results that i get without reid is pretty good, so i might chose to leave it off for the time being.

**Comment by NirAharon** [comment]
The running speed depends on your hardware.
Currently I have a weak GPU, so in the paper we report 6.6 FPS without the addition ReID module.  
If want to use the ReID module you can try to change the ReID batch_size in fast_reid/fast_reid_interfece.py line 53.

**Comment by ajtao** [comment]
Thanks again @NirAharon
