### ISSUE TITLE
Testing it for full occlusion

### ISSUE THREAD

**Issue by PranvQT** [NirAharon/BoT-SORT#7]
Hi @NirAharon Thank you for the paper and repo.. it is very impressive.
I just wanted to know weather you have tested it for full occlusion like if 2 people occlude with 100% iou will they regain their previous ids?

**Comment by NirAharon** [comment]
Hi, thank you for your interest in our work. 
We did not generate a simulation of this case, but we tested the tracker on MOT17 and MOT20 scenarios which contain full or mostly-full occlusion. To overcome full occlusion, we combined the ReID cosine distance and the IoU based on the minimum distance between them. We saw that in many or even most cases our tracker overcomes the occlusion and regains the correct ID, depending on the scenario.

**Comment by PranvQT** [comment]
Thank you @NirAharon
