### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by huanglong161** [NirAharon/BoT-SORT#8]
in fast_reid/fast_reid_interfece.py", line 75, in inference
H, W, _ = np.shape(image)
ValueError: not enough values to unpack (expected 3, got 0)
can you help me？

**Comment by NirAharon** [comment]
It seems that the image is empty. 
May you provide more information?

**Comment by huanglong161** [comment]
Thank you for your reply. This problem was solved by me yesterday, because image is a dictionary type and needs to be assigned by specifying data. It has been perfectly solved。
