### ISSUE TITLE
Is it possible to fine-tune the ReID model with images sampled from videos?

### ISSUE THREAD

**Issue by chenzhutian** [NirAharon/BoT-SORT#9]
Hi, thanks for sharing the repo, which is really awesome!
I have a dataset of images sampled from several videos.
The original framerate of the videos are 30FPS. But the images are sampled from the videos every 10 frames, i.e., a 100 frames videos are sampled as 10 images, the object in each image is labeled with id and bbox.
I am wondering if it is possible to fine-tune the ReID model with such a dataset?

Thanks!

**Comment by NirAharon** [comment]
Hi, thanks for your interest in our work.
It probably will work, maybe you will be able to find more information in the FastReID repo.
